version: '3.5'

services:
  python_pyenv_poetry_template:  ## Change this to your project name
    image: ${DOCKER_IMAGE_NAME}:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${DOCKER_CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
