version: '3.5'

services:
  python_pyenv_poetry_template:
    image: ${DOCKER_IMAGE_NAME}:latest
    command: ${ARGS}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${DOCKER_CONTAINER_NAME}
    restart: 'no'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
