# Project information
site_name: python_pyenv_poetry_template
site_url: https://github.com/bateman/python_pyenv_poetry_template
site_description: A Python Pyenv Poetry template project.
site_author: Fabio Calefato <fcalefato@gmail.com>

# Repository
repo_url: https://github.com/bateman/python_pyenv_poetry_template
repo_name: bateman/python_pyenv_poetry_template
edit_uri: "" #disables edit button

# Copyright
copyright: MIT License 2024

# Configuration
theme:
  name: readthedocs

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false

nav:
  - Home: index.md
  - Documentation:
    - Module: module.md
  - Info:
    - About: about.md
    - License: license.md
