# Project information
site_name: python_pyenv_poetry_template
site_url: https://github.com/bateman/python_pyenv_poetry_template
site_description: A Python Pyenv Poetry template project.
site_author: Fabio Calefato <fcalefato@gmail.com>

# Repository
repo_url: https://github.com/bateman/python_pyenv_poetry_template
repo_name: bateman/python_pyenv_poetry_template
edit_uri: "" #disables edit button

# Copyright
copyright: MIT License 2024

# Configuration
theme:
  name: material
  language: en
  logo: images/logo.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - github-callouts

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false

nav:
  - Home: index.md
  - Documentation:
    - Module: module.md
  - Info:
    - About: about.md
    - License: license.md
